### ISSUE TITLE
can it support docker？

### ISSUE THREAD

**Issue by gmicroul** [webOS-ports/luneos-releases#2]
can it support docker？
![image](https://github.com/user-attachments/assets/de434fd2-28af-4327-b3cc-742a6a1b80a1)

**Comment by gmicroul** [comment]
<img width="511" alt="image" src="https://github.com/user-attachments/assets/7deafe80-84a9-472e-b0c4-dbd3d94d68ac">

**Comment by Tofee** [comment]
Hi,

We never really tested docker on LuneOS. LXC works though, and we are able to run Halium in a container. We also have a (partial) support of waydroid on mainline devices.
Keep in mind that the Halium based images, like mido, use an slightly old kerne (4.9)l, and might not be able to run docker. The mainline mido image might do better, but I never tested it as I don't have that device.

So far, we don't have any usecase where docker can be useful in LuneOS, so it's not really in our todo list.

**Comment by gmicroul** [comment]
Thanks, it has been done by others.
![image](https://github.com/user-attachments/assets/1a28b29a-6adb-407e-abfd-206f6be5b825)
